/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminExperiencesRouteImport } from './routes/admin/experiences'
import { Route as AdminFormationsRouteImport } from './routes/admin/formations'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTouristsRouteImport } from './routes/admin/tourists'
import { Route as ExperiencesIdRouteImport } from './routes/experiences.$id'
import { Route as FormationsSlugRouteImport } from './routes/formations.$slug'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as MeBookingsRouteImport } from './routes/me.bookings'
import { Route as MeFormationsRouteImport } from './routes/me.formations'
import { Route as MeProfileRouteImport } from './routes/me.profile'
import { Route as MeReviewsRouteImport } from './routes/me.reviews'
import { Route as RegionsIdRouteImport } from './routes/regions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperiencesRoute = AdminExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormationsRoute = AdminFormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTouristsRoute = AdminTouristsRouteImport.update({
  id: '/tourists',
  path: '/tourists',
  getParentRoute: () => AdminRoute,
} as any)
const ExperiencesIdRoute = ExperiencesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExperiencesRoute,
} as any)
const FormationsSlugRoute = FormationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FormationsRoute,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeBookingsRoute = MeBookingsRouteImport.update({
  id: '/me/bookings',
  path: '/me/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeFormationsRoute = MeFormationsRouteImport.update({
  id: '/me/formations',
  path: '/me/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MeReviewsRoute = MeReviewsRouteImport.update({
  id: '/me/reviews',
  path: '/me/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsIdRoute = RegionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RegionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/formations': typeof FormationsRouteWithChildren
  '/regions': typeof RegionsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/formations': typeof AdminFormationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tourists': typeof AdminTouristsRoute
  '/experiences/$id': typeof ExperiencesIdRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/me/bookings': typeof MeBookingsRoute
  '/me/formations': typeof MeFormationsRoute
  '/me/profile': typeof MeProfileRoute
  '/me/reviews': typeof MeReviewsRoute
  '/regions/$id': typeof RegionsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/formations': typeof FormationsRouteWithChildren
  '/regions': typeof RegionsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/formations': typeof AdminFormationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tourists': typeof AdminTouristsRoute
  '/experiences/$id': typeof ExperiencesIdRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/me/bookings': typeof MeBookingsRoute
  '/me/formations': typeof MeFormationsRoute
  '/me/profile': typeof MeProfileRoute
  '/me/reviews': typeof MeReviewsRoute
  '/regions/$id': typeof RegionsIdRoute
  '/admin': typeof AdminIndexRoute
  '/me': typeof MeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/formations': typeof FormationsRouteWithChildren
  '/regions': typeof RegionsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/formations': typeof AdminFormationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tourists': typeof AdminTouristsRoute
  '/experiences/$id': typeof ExperiencesIdRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/me/bookings': typeof MeBookingsRoute
  '/me/formations': typeof MeFormationsRoute
  '/me/profile': typeof MeProfileRoute
  '/me/reviews': typeof MeReviewsRoute
  '/regions/$id': typeof RegionsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/experiences'
    | '/formations'
    | '/regions'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/experiences'
    | '/admin/formations'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tourists'
    | '/experiences/$id'
    | '/formations/$slug'
    | '/me/bookings'
    | '/me/formations'
    | '/me/profile'
    | '/me/reviews'
    | '/regions/$id'
    | '/admin/'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/experiences'
    | '/formations'
    | '/regions'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/experiences'
    | '/admin/formations'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tourists'
    | '/experiences/$id'
    | '/formations/$slug'
    | '/me/bookings'
    | '/me/formations'
    | '/me/profile'
    | '/me/reviews'
    | '/regions/$id'
    | '/admin'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/experiences'
    | '/formations'
    | '/regions'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/experiences'
    | '/admin/formations'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tourists'
    | '/experiences/$id'
    | '/formations/$slug'
    | '/me/bookings'
    | '/me/formations'
    | '/me/profile'
    | '/me/reviews'
    | '/regions/$id'
    | '/admin/'
    | '/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  FormationsRoute: typeof FormationsRouteWithChildren
  RegionsRoute: typeof RegionsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MeBookingsRoute: typeof MeBookingsRoute
  MeFormationsRoute: typeof MeFormationsRoute
  MeProfileRoute: typeof MeProfileRoute
  MeReviewsRoute: typeof MeReviewsRoute
  MeIndexRoute: typeof MeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences': {
      id: '/admin/experiences'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof AdminExperiencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formations': {
      id: '/admin/formations'
      path: '/formations'
      fullPath: '/admin/formations'
      preLoaderRoute: typeof AdminFormationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tourists': {
      id: '/admin/tourists'
      path: '/tourists'
      fullPath: '/admin/tourists'
      preLoaderRoute: typeof AdminTouristsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/experiences/$id': {
      id: '/experiences/$id'
      path: '/$id'
      fullPath: '/experiences/$id'
      preLoaderRoute: typeof ExperiencesIdRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/formations/$slug': {
      id: '/formations/$slug'
      path: '/$slug'
      fullPath: '/formations/$slug'
      preLoaderRoute: typeof FormationsSlugRouteImport
      parentRoute: typeof FormationsRoute
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/bookings': {
      id: '/me/bookings'
      path: '/me/bookings'
      fullPath: '/me/bookings'
      preLoaderRoute: typeof MeBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/formations': {
      id: '/me/formations'
      path: '/me/formations'
      fullPath: '/me/formations'
      preLoaderRoute: typeof MeFormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/reviews': {
      id: '/me/reviews'
      path: '/me/reviews'
      fullPath: '/me/reviews'
      preLoaderRoute: typeof MeReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/$id': {
      id: '/regions/$id'
      path: '/$id'
      fullPath: '/regions/$id'
      preLoaderRoute: typeof RegionsIdRouteImport
      parentRoute: typeof RegionsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminExperiencesRoute: typeof AdminExperiencesRoute
  AdminFormationsRoute: typeof AdminFormationsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTouristsRoute: typeof AdminTouristsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminExperiencesRoute: AdminExperiencesRoute,
  AdminFormationsRoute: AdminFormationsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTouristsRoute: AdminTouristsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExperiencesRouteChildren {
  ExperiencesIdRoute: typeof ExperiencesIdRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesIdRoute: ExperiencesIdRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

interface FormationsRouteChildren {
  FormationsSlugRoute: typeof FormationsSlugRoute
}

const FormationsRouteChildren: FormationsRouteChildren = {
  FormationsSlugRoute: FormationsSlugRoute,
}

const FormationsRouteWithChildren = FormationsRoute._addFileChildren(
  FormationsRouteChildren,
)

interface RegionsRouteChildren {
  RegionsIdRoute: typeof RegionsIdRoute
}

const RegionsRouteChildren: RegionsRouteChildren = {
  RegionsIdRoute: RegionsIdRoute,
}

const RegionsRouteWithChildren =
  RegionsRoute._addFileChildren(RegionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  FormationsRoute: FormationsRouteWithChildren,
  RegionsRoute: RegionsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MeBookingsRoute: MeBookingsRoute,
  MeFormationsRoute: MeFormationsRoute,
  MeProfileRoute: MeProfileRoute,
  MeReviewsRoute: MeReviewsRoute,
  MeIndexRoute: MeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
