package ma.lbledfirst.backend.domain;

public enum RegionName {
    TANGER_TETOUAN_AL_HOCEIMA,
    LORIENTAL,
    FES_MEKNES,
    RABAT_SALE_KENITRA,
    BENI_MELLAL_KHENIFRA,
    CASABLANCA_SETTAT,
    MARRAKECH_SAFI,
    DRAA_TAFILALET,
    SOUSS_MASSA,
    GUELMIM_OUED_NOUN,
    LAAYOUNE_SAKIA_EL_HAMRA,
    DAKHLA_OUED_ED_DAHAB
}
