spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

cookie:
  secure: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
