spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

cookie:
  secure: true

management:
  endpoints:
    web:
      exposure:
        include: health
