// Simple country list (name + flag emoji) for the auth combobox.
// Not exhaustive ISO — the top ~60 markets for L'Bled First's audience.
export type Country = { code: string; name: string; flag: string };

export const COUNTRIES: Country[] = [
    { code: "MA", name: "Maroc", flag: "🇲🇦" },
    { code: "FR", name: "France", flag: "🇫🇷" },
    { code: "ES", name: "España", flag: "🇪🇸" },
    { code: "PT", name: "Portugal", flag: "🇵🇹" },
    { code: "IT", name: "Italia", flag: "🇮🇹" },
    { code: "DE", name: "Deutschland", flag: "🇩🇪" },
    { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
    { code: "IE", name: "Ireland", flag: "🇮🇪" },
    { code: "NL", name: "Nederland", flag: "🇳🇱" },
    { code: "BE", name: "Belgique", flag: "🇧🇪" },
    { code: "CH", name: "Suisse", flag: "🇨🇭" },
    { code: "AT", name: "Österreich", flag: "🇦🇹" },
    { code: "SE", name: "Sverige", flag: "🇸🇪" },
    { code: "NO", name: "Norge", flag: "🇳🇴" },
    { code: "DK", name: "Danmark", flag: "🇩🇰" },
    { code: "FI", name: "Suomi", flag: "🇫🇮" },
    { code: "PL", name: "Polska", flag: "🇵🇱" },
    { code: "CZ", name: "Česko", flag: "🇨🇿" },
    { code: "GR", name: "Ελλάδα", flag: "🇬🇷" },
    { code: "TR", name: "Türkiye", flag: "🇹🇷" },
    { code: "RU", name: "Россия", flag: "🇷🇺" },
    { code: "UA", name: "Україна", flag: "🇺🇦" },
    { code: "US", name: "United States", flag: "🇺🇸" },
    { code: "CA", name: "Canada", flag: "🇨🇦" },
    { code: "MX", name: "México", flag: "🇲🇽" },
    { code: "BR", name: "Brasil", flag: "🇧🇷" },
    { code: "AR", name: "Argentina", flag: "🇦🇷" },
    { code: "CL", name: "Chile", flag: "🇨🇱" },
    { code: "CO", name: "Colombia", flag: "🇨🇴" },
    { code: "PE", name: "Perú", flag: "🇵🇪" },
    { code: "DZ", name: "Algérie", flag: "🇩🇿" },
    { code: "TN", name: "Tunisie", flag: "🇹🇳" },
    { code: "EG", name: "مصر", flag: "🇪🇬" },
    { code: "SN", name: "Sénégal", flag: "🇸🇳" },
    { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮" },
    { code: "ZA", name: "South Africa", flag: "🇿🇦" },
    { code: "NG", name: "Nigeria", flag: "🇳🇬" },
    { code: "KE", name: "Kenya", flag: "🇰🇪" },
    { code: "SA", name: "السعودية", flag: "🇸🇦" },
    { code: "AE", name: "الإمارات", flag: "🇦🇪" },
    { code: "QA", name: "قطر", flag: "🇶🇦" },
    { code: "KW", name: "الكويت", flag: "🇰🇼" },
    { code: "JO", name: "الأردن", flag: "🇯🇴" },
    { code: "LB", name: "لبنان", flag: "🇱🇧" },
    { code: "IL", name: "ישראל", flag: "🇮🇱" },
    { code: "IN", name: "India", flag: "🇮🇳" },
    { code: "PK", name: "Pakistan", flag: "🇵🇰" },
    { code: "CN", name: "中国", flag: "🇨🇳" },
    { code: "JP", name: "日本", flag: "🇯🇵" },
    { code: "KR", name: "한국", flag: "🇰🇷" },
    { code: "TH", name: "ประเทศไทย", flag: "🇹🇭" },
    { code: "VN", name: "Việt Nam", flag: "🇻🇳" },
    { code: "ID", name: "Indonesia", flag: "🇮🇩" },
    { code: "PH", name: "Philippines", flag: "🇵🇭" },
    { code: "AU", name: "Australia", flag: "🇦🇺" },
    { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
];
